#### Determinging HPV status

In conjunction with known HPV status from Nulton et al:

https://pmc.ncbi.nlm.nih.gov/articles/PMC5392278/#_

it was found that 75 patients were HPV+, moved forward in this manner

These are highly validated HPV+ cases

#### libraries

In [1]:
import pandas as pd
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import plotly.express as px

#### Combine paper and travis case IDs as hpv positive case ids

In [3]:
### paper identified known HPV positive cases and files
paper_hpv_positive_case_ids = pd.read_csv('Data/Supplementary data Nulton/2. HNC HPV Types.csv')['HNSCC Barcode'].tolist()
paper_hpv_all_case_ids = pd.read_csv('Data/Supplementary data Nulton/TCGA CASE ID.csv')['TCGA CASE ID'].tolist()
### convert to only case ids
paper_hpv_all_case_ids = [x.split('-')[0] + '-' + x.split('-')[1] + '-' + x.split('-')[2] for x in paper_hpv_all_case_ids]

print("number of unique case ids from paper for HPV positive cases: ", len(set(paper_hpv_positive_case_ids)))
print("number of unique case ids from paper for all cases: ", len(set(paper_hpv_all_case_ids)))

number of unique case ids from paper for HPV positive cases:  72
number of unique case ids from paper for all cases:  520

In [4]:
### Somatic mutation data
# somatic_mutation = pd.read_csv('Data/TCGA/SOM/cohortMAF.2025-11-12.maf', sep= '\t')
# somatic_mutation['Case ID'] = somatic_mutation['Tumor_Sample_Barcode'].str.split('-').str[0:3].str.join('-').tolist()

In [ ]:
### Somatic mutation data
somatic_mutation = pd.read_csv('Data/TCGA/SOM/cohortMAF.2025-07-29.maf', sep= '\t')
somatic_mutation['Case ID'] = somatic_mutation['Tumor_Sample_Barcode'].str.split('-').str[0:3].str.join('-').tolist()

### filter to nulton SOM cohort for use in downstream analyses
nulton_somatic_cohort = somatic_mutation[somatic_mutation['Case ID'].isin(paper_hpv_all_case_ids)]
nulton_somatic_cohort.to_csv('Data/TCGA/SOM/nulton_somatic_mutation_cohort.csv', index= False)

/var/folders/5p/swntgnbj3fbfxkx02kt3fq980000gn/T/ipykernel_3254/3183650318.py:2: DtypeWarning: Columns (31,120) have mixed types. Specify dtype option on import or set low_memory=False.
  somatic_mutation = pd.read_csv('Data/TCGA/SOM/cohortMAF.2025-07-29.maf', sep= '\t')

In [6]:
somatic_mutation

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,...,COSMIC,hotspot,tumor_bam_uuid,normal_bam_uuid,RNA_Support,RNA_depth,RNA_ref_count,RNA_alt_count,callers,Case ID
0,ID3,3399,BCM,GRCh38,chr1,23559199,23559199,+,Nonsense_Mutation,SNP,...,NaN,N,0b2f9bc9-a959-4327-95ac-8abc8eb0f94d,0709be17-c4b4-47b5-83f5-27623da417cc,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-FF-8046
1,LRRC8D,55144,BCM,GRCh38,chr1,89935851,89935851,+,3'UTR,SNP,...,NaN,N,0b2f9bc9-a959-4327-95ac-8abc8eb0f94d,0709be17-c4b4-47b5-83f5-27623da417cc,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-FF-8046
2,NHLH2,4808,BCM,GRCh38,chr1,115839030,115839030,+,Intron,SNP,...,NaN,N,0b2f9bc9-a959-4327-95ac-8abc8eb0f94d,0709be17-c4b4-47b5-83f5-27623da417cc,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-FF-8046
3,ITGA10,8515,BCM,GRCh38,chr1,145906764,145906764,+,Missense_Mutation,SNP,...,NaN,N,0b2f9bc9-a959-4327-95ac-8abc8eb0f94d,0709be17-c4b4-47b5-83f5-27623da417cc,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-FF-8046
4,ARHGEF11,9826,BCM,GRCh38,chr1,156971704,156971704,+,Intron,SNP,...,NaN,N,0b2f9bc9-a959-4327-95ac-8abc8eb0f94d,0709be17-c4b4-47b5-83f5-27623da417cc,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-FF-8046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116309,C19orf47,126526,BI,GRCh38,chr19,40322053,40322053,+,Missense_Mutation,SNP,...,NaN,N,45ec8d82-e4e6-4eb9-b3a0-6a16d929fcc9,3761a520-1166-4383-97af-2c3244c7f58f,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-MZ-A6I9
116310,ZNF155,7711,BI,GRCh38,chr19,43996817,43996825,+,In_Frame_Del,DEL,...,NaN,N,45ec8d82-e4e6-4eb9-b3a0-6a16d929fcc9,3761a520-1166-4383-97af-2c3244c7f58f,Unknown,NaN,NaN,NaN,mutect2;pindel;varscan2,TCGA-MZ-A6I9
116311,ZNF135,7694,BI,GRCh38,chr19,58068051,58068051,+,Nonsense_Mutation,SNP,...,NaN,N,45ec8d82-e4e6-4eb9-b3a0-6a16d929fcc9,3761a520-1166-4383-97af-2c3244c7f58f,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-MZ-A6I9
116312,FOXR2,139628,BI,GRCh38,chrX,55623864,55623864,+,Silent,SNP,...,NaN,N,45ec8d82-e4e6-4eb9-b3a0-6a16d929fcc9,3761a520-1166-4383-97af-2c3244c7f58f,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-MZ-A6I9
116313,TENM1,10178,BI,GRCh38,chrX,124381200,124381200,+,Missense_Mutation,SNP,...,NaN,N,45ec8d82-e4e6-4eb9-b3a0-6a16d929fcc9,3761a520-1166-4383-97af-2c3244c7f58f,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2,TCGA-MZ-A6I9

In [7]:
nulton_somatic_cohort['Hugo_Symbol'].nunique()

16477

In [8]:
nulton_somatic_cohort['Case ID'].nunique()

499

In [9]:
### number of unique cases in the overall paper cohort
print("number of unique case ids from paper for all cases: ", len(set(paper_hpv_all_case_ids)))
### overlap of all case ids and positive case ids from paper
overlap_case_ids = set(paper_hpv_all_case_ids).intersection(set(paper_hpv_positive_case_ids))
print("number of overlapping case ids between all cases and positive cases from paper: ", len(overlap_case_ids))

### number of hpv negatie cases in paper cohort
paper_hpv_negative_case_ids = list(set(paper_hpv_all_case_ids) - set(paper_hpv_positive_case_ids))
print("number of unique case ids from paper for HPV negative cases: ", len(set(paper_hpv_negative_case_ids)))

number of unique case ids from paper for all cases:  520
number of overlapping case ids between all cases and positive cases from paper:  72
number of unique case ids from paper for HPV negative cases:  448

In [10]:
### identify HPV negative cases
paper_hpv_negative_case_ids = list(set(paper_hpv_all_case_ids) - set(paper_hpv_positive_case_ids))
print("number of unique case ids from paper for HPV negative cases: ", len(set(paper_hpv_negative_case_ids)))

number of unique case ids from paper for HPV negative cases:  448

In [11]:
HPV_POSITIVE_DF = pd.DataFrame()
HPV_POSITIVE_DF['TCGA CASE ID'] = paper_hpv_positive_case_ids
HPV_POSITIVE_DF.to_csv('Results/HPV results/HPV positive patients.csv')

HPV_NEGATIVE_DF = pd.DataFrame()
HPV_NEGATIVE_DF['TCGA CASE ID'] = paper_hpv_negative_case_ids
HPV_NEGATIVE_DF.to_csv('Results/HPV results/HPV negative patients.csv')

In [12]:
HPV_POSITIVE_DF

    TCGA CASE ID
0   TCGA-HD-A634
1   TCGA-P3-A5QE
2   TCGA-BA-A4IH
3   TCGA-BB-7866
4   TCGA-DQ-7596
..           ...
67  TCGA-CV-6939
68  TCGA-DQ-7591
69  TCGA-IQ-A61I
70  TCGA-HD-8314
71  TCGA-BB-7864

[72 rows x 1 columns]

In [13]:
HPV_NEGATIVE_DF

     TCGA CASE ID
0    TCGA-CN-A63T
1    TCGA-UF-A71E
2    TCGA-CR-7367
3    TCGA-KU-A66S
4    TCGA-CR-6477
..            ...
443  TCGA-CR-7374
444  TCGA-CV-7103
445  TCGA-BB-8601
446  TCGA-CN-4742
447  TCGA-BA-4075

[448 rows x 1 columns]